version: "3"
services:
  https:
    # XXX Use image: tecnativa/haproxy-letsencrypt instead
    image: tecnativa/haproxy-letsencrypt
    container_name: haproxy
    build: .
    environment:
      # XXX: Fill this with your real data
      DOMAINS: emby.example.com
      EMAIL: embyuser@gmail.com
      # XXX: Use "false" to get real certs!
      STAGING: "true"
      # XXX: Use "true" when cert fetching should fail (i.e. in dev env)
      CONTINUE_ON_CERTONLY_FAILURE: "false"
    links:
      - "emby-server:emby-server"
      - www
    ports:
      # It's important to have real ports handled by this container
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # This keeps certs and cronstamps across reloads
      # Change the dir to where you store the files
      - /home/user/docker_vol/haproxy/letsencrypt:/etc/letsencrypt
      - /home/user/docker_vol/haproxy/cronstamps:/var/spool/cron/cronstamps
      - /home/user/docker_vol/haproxy/conf:/etc/haproxy:ro

  emby-server:
    image: nvllsvm/emby-unlocked
    container_name: emby-server
    environment:
      TZ: America/New_York
    volumes:
      - "/path/to/emby-server/config:/config"
      - "/path/to/media/files:/storage"





    # XXX: Put your web app here; for testing, this one is very useful
    www:
        image: stackatoapps/phpinfo
